metrics:
  configs:
    - name: app-scrapping
      scrape_configs:
        - job_name: 'spring-app-1'
          metrics_path: /metrics
          static_configs:
            - targets: [ 'host.docker.internal:8081' ]
        - job_name: 'spring-app-2'
          metrics_path: /metrics
          static_configs:
            - targets: [ 'host.docker.internal:8082' ]
      remote_write:
        - url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
          basic_auth:
            username: 1340025
            password:

traces:
  configs:
    - name: default
      receivers:
        zipkin:
      remote_write:
        - endpoint: tempo-prod-10-prod-eu-west-2.grafana.net:443
          basic_auth:
            username: 767819
            password:
      batch:
        timeout: 5s
        send_batch_size: 100